name: Docker Prueba
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v4
      - name: Run Docker Container
        uses: tonys-code-base/run-container-action@v1.0.0
        with:
          # Docker registry address
          # Image name
          image: ubuntu
          # Image tag
          tag: latest
          
