name: Docker Prueba
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v4
      - name: Run Docker Container
        run: docker run ubuntu bash -c "echo 'Hello, World!'"
