name: Stats
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run
        run: ./Roadmap/stats.py
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: aqui probando github actions
          commit_user_name: yo mismo
        
